#[cfg(not(target_arch = "wasm32"))]
pub mod asset_watcher;
pub mod camera;
pub mod egui_bridge;
pub mod egui_pass;
pub mod geometry;
pub mod gpu_context;
pub mod instancing;
pub mod material;
pub mod model_loader;
pub mod pipeline;
pub mod sky;
mod sky_pass;
pub mod terrain_compute;
pub mod thumbnail;
pub mod world;

pub(crate) mod blur_pass;
mod frustum;
mod grass_pass;
mod hud_font;
mod hud_pass;
mod instanced_pass;
mod minimap_colors;
mod minimap_pass;
mod river_normal_texture;
mod river_pass;
mod sign_text;
mod terrain_pass;
mod terrain_texture;
mod water_pass;
